FROM openjdk:8u191-jre-alpine3.8

#Workspace
WORKDIR /usr/share/udemy

ADD target/selenium-docker.jar selenium-docker.jar
ADD target/selenium-docker-tests.jar selenium-docker-tests.jar
ADD target/libs libs

#if any other dependency like .csv/ .json
#Add that as well


#ADD Suite files
ADD testng.xml testng.xml
ADD search-module.xml search-module.xml

#BROWSER
#HUB_HOST
#MODULE

ENTRYPOINT java -cp selenium-docker.jar;selenium-docker-tests.jar;libs/* -DBROWSER=$BROWSER DHUB_HOST=$HUB_HOST org.testng.TestNG $MODULE
